version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root  # Указываем здесь явно
    ports:
      - "3307:3306"  # локальный порт 3307 -> контейнерный 3306
    volumes:
      - db_data:/var/lib/mysql
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db 
    depends_on:
      - db

volumes:
  db_data:
